name: PDF Build and Deploy

on:
  workflow_run:
    workflows: ["Initial Build and Deploy"]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read 

jobs:
  pdf-all:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: &company-matrix
        company: [default, clario, mercury]
    steps:
      - name: Download company artifact
        uses: actions/download-artifact@v4
        with:
          name: out-${{ matrix.company }}
          path: out-${{ matrix.company }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate PDF
        uses: narthanaj/html-to-pdf-action@v1.0.0
        with:
          # Root for default, /company/ for others
          source: https://vbanderov.github.io/svelte-cv/${{ matrix.company == 'default' && 'index.html' || format('{0}/index.html', matrix.company) }}#${{ secrets.ENCRYPTION_PASSWORD }}
          output: out-${{ matrix.company }}/${{ secrets.ENCRYPTION_PASSWORD }}.pdf
          print_background: 'true'

      - name: Upload updated artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-out-${{ matrix.company }}
          path: out-${{ matrix.company }}

  deploy-with-pdf:
    needs: pdf-all
    runs-on: ubuntu-latest
    steps:
      - name: Download all Final Artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-final
          pattern: final-out-*
          merge-multiple: false

      - name: Combine with Root Logic
        run: |
          mkdir -p build
          for d in all-final/final-out-*; do
            company=$(basename "$d" | sed 's/^final-out-//')
            if [ "$company" = "default" ]; then
              cp -r "$d"/* build/
            else
              mkdir -p build/$company
              cp -r "$d"/* build/$company/
            fi
          done

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'build/'

      - name: Deploy
        uses: actions/deploy-pages@v4

  delete-build-artifacts:
    needs: deploy-with-pdf
    runs-on: ubuntu-latest
    strategy:
      matrix: *company-matrix
    steps:
      - name: Delete build artifact
        uses: geekyeggo/delete-artifact@v5.1.0
        with:
          name: out-${{ matrix.company }}
      - name: Delete final build artifact
        uses: geekyeggo/delete-artifact@v5.1.0
        with:
          name: final-out-${{ matrix.company }}
